[project]
name = "blog-app-fastapi"
version = "0.1.0"
description = "A FastAPI blog API with async PostgreSQL and SQLModel"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "bcrypt==4.0.1",
    "fastapi[all]>=0.136.1",
    "greenlet>=3.5.1",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.13.0",
    "redis[hiredis]>=7.4.0",
    "scalar-fastapi>=1.8.2",
    "sqlmodel>=0.0.38",
]
