"""Updated models added likes and bookmarks

Revision ID: d32a46064e90
Revises: 70bc71916e8b
Create Date: 2026-06-29 16:01:10.420018

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d32a46064e90"
down_revision: Union[str, Sequence[str], None] = "70bc71916e8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tag_slug"), table_name="tag")
    op.drop_column("tag", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tag",
        sa.Column("slug", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_tag_slug"), "tag", ["slug"], unique=True)
    # ### end Alembic commands ###
