"""Initial Models

Revision ID: fd9f4cd81b8d
Revises: 16de71a1f2b6
Create Date: 2026-06-27 17:55:31.588650

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd9f4cd81b8d"
down_revision: Union[str, Sequence[str], None] = "16de71a1f2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("parent_comment_id", sa.Uuid(), nullable=True))
    op.add_column("comment", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "comment",
        "content",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_comment_author_id"), "comment", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_comment_created_at"), "comment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_comment_parent_comment_id"),
        "comment",
        ["parent_comment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_comment_post_id"), "comment", ["post_id"], unique=False)
    op.create_foreign_key(None, "comment", "comment", ["parent_comment_id"], ["id"])
    op.add_column(
        "post",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    )
    op.add_column(
        "post",
        sa.Column(
            "excerpt", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
    )

    # --- PostStatus Enum Creation ---
    poststatus_enum = postgresql.ENUM(
        "DRAFT", "PUBLISHED", "ARCHIVED", name="poststatus"
    )
    poststatus_enum.create(op.get_bind(), checkfirst=True)
    # --------------------------------

    op.add_column(
        "post",
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="poststatus"),
            nullable=False,
        ),
    )
    op.add_column("post", sa.Column("published_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "post",
        "content",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_post_title"), table_name="post")
    op.create_index(op.f("ix_post_author_id"), "post", ["author_id"], unique=False)
    op.create_index(
        op.f("ix_post_published_at"), "post", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_post_slug"), "post", ["slug"], unique=True)
    op.create_index(op.f("ix_post_status"), "post", ["status"], unique=False)
    op.drop_column("post", "published_status")
    op.add_column(
        "tag",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    )
    op.add_column("tag", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.create_index(op.f("ix_tag_slug"), "tag", ["slug"], unique=True)
    op.create_unique_constraint(None, "tag", ["name"])
    op.add_column(
        "user",
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("biography", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    # --- UserRole Enum Creation ---
    userrole_enum = postgresql.ENUM("ADMIN", "AUTHOR", "READER", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)
    # ------------------------------

    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "AUTHOR", "READER", name="userrole"),
            nullable=False,
        ),
    )
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.drop_column("user", "role")
    op.drop_column("user", "avatar_url")
    op.drop_column("user", "biography")
    op.drop_column("user", "display_name")
    op.drop_constraint(None, "tag", type_="unique")
    op.drop_index(op.f("ix_tag_slug"), table_name="tag")
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.drop_column("tag", "created_at")
    op.drop_column("tag", "slug")
    op.add_column(
        "post",
        sa.Column(
            "published_status", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_post_status"), table_name="post")
    op.drop_index(op.f("ix_post_slug"), table_name="post")
    op.drop_index(op.f("ix_post_published_at"), table_name="post")
    op.drop_index(op.f("ix_post_author_id"), table_name="post")
    op.create_index(op.f("ix_post_title"), "post", ["title"], unique=False)
    op.alter_column(
        "post",
        "content",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("post", "published_at")
    op.drop_column("post", "status")
    op.drop_column("post", "excerpt")
    op.drop_column("post", "slug")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_index(op.f("ix_comment_post_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_parent_comment_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_created_at"), table_name="comment")
    op.drop_index(op.f("ix_comment_author_id"), table_name="comment")
    op.alter_column(
        "comment",
        "content",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("comment", "deleted_at")
    op.drop_column("comment", "parent_comment_id")
    # ### end Alembic commands ###
